PANEL_HTML = r'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Scalping AI Control Panel</title>
<style>
:root{--bg:#071019;--panel:#0c1721;--panel2:#0a131c;--line:#1e3040;--text:#eef6fb;--mut:#87a0b4;--green:#39d487;--red:#ff575f;--amber:#f7c843;--cyan:#26c9ff;--blue:#1b76a8}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#061019,#08111a);color:var(--text);font-family:Inter,Segoe UI,Arial,sans-serif}.wrap{max-width:1540px;margin:auto;padding:12px}.top{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:8px}.title h1{margin:0;font-size:26px}.sub{color:var(--mut);font-size:13px}.statusbar{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.badge{padding:7px 10px;border:1px solid var(--line);border-radius:10px;font-size:12px;font-weight:800;background:#0b151e;color:var(--mut)}.badge.ok{color:#9df0c3;border-color:#275a43;background:#0b2e22}.badge.bad{color:#ff9ba1;border-color:#653038;background:#32171b}.badge.wait{color:#ffe08b;border-color:#685b27;background:#302a12}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:8px}.card{background:linear-gradient(180deg,var(--panel),var(--panel2));border:1px solid var(--line);border-radius:12px;padding:12px}.s3{grid-column:span 3}.s4{grid-column:span 4}.s5{grid-column:span 5}.s6{grid-column:span 6}.s7{grid-column:span 7}.s8{grid-column:span 8}.s9{grid-column:span 9}.s12{grid-column:span 12}.label{font-size:11px;color:var(--mut);text-transform:uppercase;letter-spacing:.04em}.metric{font-size:25px;font-weight:800;margin-top:5px}.green{color:var(--green)}.red{color:var(--red)}.amber{color:var(--amber)}.mut{color:var(--mut)}
.stats{display:grid;grid-template-columns:1.25fr repeat(5,1fr);gap:8px}.stat{padding:11px 14px;border-right:1px solid var(--line)}.stat:last-child{border-right:0}.statv{font-size:21px;font-weight:800;margin-top:4px}.symrow{display:flex;align-items:center;gap:10px}.coin{width:34px;height:34px;border-radius:50%;background:#f3a52a;color:#fff;display:flex;align-items:center;justify-content:center;font-weight:900}.symselect{background:#0a151f;border:1px solid var(--line);color:#fff;padding:8px 10px;border-radius:8px;font-weight:800}.btns{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.btn{padding:12px;border:0;border-radius:8px;color:#fff;font-weight:800;cursor:pointer;font-size:14px}.start{background:#0a743d;border:1px solid #1a9a59}.stop{background:#53697b}.emg{background:#a5282e;border:1px solid #d7494f}.close{background:#351419;border:1px solid #9e333a}.btn:hover{filter:brightness(1.08)}
.search{display:flex;align-items:center;justify-content:space-between;gap:8px;background:#101924;border:1px solid var(--line);border-radius:8px;padding:8px 10px;margin-bottom:8px}.pulse{width:9px;height:9px;border-radius:50%;background:var(--amber);display:inline-block;box-shadow:0 0 10px var(--amber);animation:p 1s infinite}@keyframes p{0%,100%{opacity:.35}50%{opacity:1}}.signal{font-size:28px;font-weight:900}.sentiment{display:grid;grid-template-columns:1fr 150px 1fr;align-items:center;gap:10px;margin:10px 0}.sidebox{padding:10px;border:1px solid var(--line);border-radius:10px;background:#09131c}.sidepct{font-size:28px;font-weight:900}.gauge{width:124px;height:124px;border-radius:50%;margin:auto;display:grid;place-items:center;background:conic-gradient(var(--green) 0deg 180deg,var(--red) 180deg 360deg);position:relative}.gauge:after{content:'';position:absolute;width:88px;height:88px;border-radius:50%;background:#0b151e}.gaugein{position:relative;z-index:2;text-align:center}.gaugein b{font-size:25px}.split{height:14px;background:linear-gradient(90deg,var(--green) 0 50%,var(--red) 50% 100%);border-radius:999px;position:relative;overflow:hidden}.splitmarker{position:absolute;top:0;bottom:0;width:3px;background:#fff;left:50%}.direction{display:flex;justify-content:space-between;gap:10px;margin-top:8px;font-size:13px}.chips{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:10px}.chip{padding:8px;border:1px solid var(--line);border-radius:8px;background:#09131c;text-align:center;font-size:11px}.chip b{display:block;margin-top:4px}
.marketMood{margin-top:10px}.moodTrack{height:18px;border-radius:999px;background:linear-gradient(90deg,#a7242b,#f08a32,#aaa,#3bcf83);position:relative}.moodNeedle{position:absolute;top:-5px;width:4px;height:28px;background:#fff;left:50%;border-radius:2px}.moodLabels{display:flex;justify-content:space-between;font-size:10px;color:var(--mut);margin-top:4px}
.bookwrap{display:grid;grid-template-columns:1fr 110px 1fr;gap:8px;align-items:start}.booktitle{font-size:18px;font-weight:800;margin:0 0 6px}.book table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:5px 6px;border-bottom:1px solid #172838;text-align:right}th:first-child,td:first-child{text-align:left}.midcol{display:flex;flex-direction:column;gap:10px;align-items:center;justify-content:center;padding-top:52px}.lastprice{font-size:22px;font-weight:900}.spread{font-size:11px;color:var(--mut);text-align:center}.dom{margin-top:8px;padding:9px;border:1px solid var(--line);border-radius:9px}.domline{height:12px;border-radius:999px;background:linear-gradient(90deg,var(--green) 0 50%,var(--red) 50% 100%);margin:6px 0}.domnums{display:flex;justify-content:space-between;font-weight:800;font-size:13px}
.bottom{display:grid;grid-template-columns:1.2fr .7fr 1.1fr;gap:8px}.log{height:112px;overflow:auto;background:#061019;border:1px solid var(--line);border-radius:8px;padding:8px;font:11px ui-monospace,Consolas,monospace;white-space:pre-wrap}.foot{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;color:var(--mut);font-size:11px;padding:8px 4px 0}
@media(max-width:1100px){.s3,.s4,.s5,.s6,.s7,.s8,.s9{grid-column:span 12}.stats{grid-template-columns:1fr 1fr 1fr}.sentiment{grid-template-columns:1fr}.bookwrap{grid-template-columns:1fr}.midcol{padding-top:0;flex-direction:row}.bottom{grid-template-columns:1fr}.btns{grid-template-columns:1fr 1fr}}@media(max-width:600px){.wrap{padding:7px}.stats{grid-template-columns:1fr 1fr}.btns{grid-template-columns:1fr}.title h1{font-size:22px}.metric{font-size:22px}.chips{grid-template-columns:1fr 1fr}.statusbar{justify-content:flex-start}}
</style></head><body><div class="wrap">
<div class="top"><div class="title"><h1>Scalping AI Control Panel <span class="green" style="font-size:14px">v0.5.3</span></h1><div class="sub">DEMO execution + LIVE Binance USD-M WebSocket</div></div><div class="statusbar"><span id="serverBadge" class="badge wait">SERVER • CHECK</span><span id="binanceBadge" class="badge wait">BINANCE • CONNECTING</span><span id="botBadge" class="badge bad">BOT • STOPPED</span><span id="liveAge" class="badge">LIVE —</span></div></div>

<div class="card" style="padding:0 4px;margin-bottom:8px"><div class="stats">
<div class="stat"><div class="symrow"><div class="coin" id="coinIcon">₿</div><div><select id="marketSymbol" class="symselect" onchange="connectWs()"><option>BTCUSDT</option><option>ETHUSDT</option><option>BNBUSDT</option><option>SOLUSDT</option></select><div class="mut" style="font-size:11px;margin-top:3px">Perpetual</div></div></div></div>
<div class="stat"><div class="label">Live price</div><div id="livePrice" class="statv green">—</div><div class="mut" style="font-size:11px">Mark: <span id="markPrice">—</span></div></div>
<div class="stat"><div class="label">24h change</div><div id="change24" class="statv">—</div><div class="mut" style="font-size:11px"><span id="changeAbs">—</span></div></div>
<div class="stat"><div class="label">24h high</div><div id="high24" class="statv">—</div></div>
<div class="stat"><div class="label">24h low</div><div id="low24" class="statv">—</div></div>
<div class="stat"><div class="label">Funding / countdown</div><div id="funding" class="statv">—</div><div class="mut" style="font-size:11px"><span id="fundingCd">—</span></div></div>
</div></div>

<div class="card" style="margin-bottom:8px"><div class="btns"><button class="btn start" onclick="startBot()">▶ AUTO START</button><button class="btn stop" onclick="stopBot()">Ⅱ STOP AUTO</button><button class="btn emg" onclick="emergency()">⚠ EMERGENCY STOP</button><button class="btn close" onclick="closeAll()">✕ CLOSE ALL POSITIONS</button></div></div>

<div class="grid">
<div class="card s5"><div class="label">Текущий сигнал</div><div class="search"><span><span id="searchDot" class="pulse" style="display:none"></span> <b id="searchText">ПОИСК ОСТАНОВЛЕН</b></span><span class="mut" style="font-size:11px">анализ <span id="analysisAge">—</span></span></div>
<div id="signalLine" class="signal amber">HOLD</div>
<div class="sentiment"><div class="sidebox"><div class="label green">BUY / LONG</div><div id="buyPct" class="sidepct green">50%</div><div id="buyArrow" class="green">↗</div></div><div class="gauge" id="scoreGauge"><div class="gaugein"><b id="conf">0%</b><div class="mut" style="font-size:10px">CONFIDENCE</div></div></div><div class="sidebox" style="text-align:right"><div class="label red">SELL / SHORT</div><div id="sellPct" class="sidepct red">50%</div><div id="sellArrow" class="red">↘</div></div></div>
<div class="split"><div id="splitMarker" class="splitmarker"></div></div>
<div class="direction"><span>НАПРАВЛЕНИЕ: <b id="direction" class="amber">НЕОПРЕДЕЛЕННО</b></span><span>ПОРОГ ВХОДА: <b id="threshold">77%</b></span></div>
<div class="chips"><div class="chip">MARKET<b id="marketState">—</b></div><div class="chip">RSI<b id="rsi">—</b></div><div class="chip">ADX<b id="adx">—</b></div><div class="chip">VOLUME<b id="volRatio">—</b></div><div class="chip">ENTRY<b id="entry">—</b></div></div>
<div class="marketMood"><div class="label">Настрой рынка — совокупный score стратегии + стакан</div><div class="moodTrack"><div id="moodNeedle" class="moodNeedle"></div></div><div class="moodLabels"><span>STRONG SELL</span><span>NEUTRAL</span><span>STRONG BUY</span></div><div style="display:flex;justify-content:space-between;margin-top:5px;font-size:12px"><span id="moodText" class="amber">NEUTRAL</span><span>SL <b id="sl">—</b> · TP <b id="tp">—</b></span></div></div>
</div>

<div class="card s7"><div class="label">Стакан ордеров LIVE</div><div class="bookwrap"><div class="book"><div class="booktitle red">ПРОДАЖА / ASK</div><table><thead><tr><th>Цена</th><th>Кол-во</th><th>Всего</th></tr></thead><tbody id="asks"></tbody></table></div><div class="midcol"><div class="spread">СПРЕД<br><b id="spread">—</b></div><div id="lastPriceMid" class="lastprice green">—</div><div class="spread">LAST PRICE</div></div><div class="book"><div class="booktitle green">ПОКУПКА / BID</div><table><thead><tr><th>Цена</th><th>Кол-во</th><th>Всего</th></tr></thead><tbody id="bids"></tbody></table></div></div>
<div class="dom"><div class="label">Преимущество стакана</div><div class="domnums"><span id="bidDom" class="green">50%</span><span id="askDom" class="red">50%</span></div><div id="domLine" class="domline"></div><div style="display:flex;justify-content:space-between;font-size:11px;color:var(--mut)"><span>Bid volume: <b id="bidVol">—</b></span><span>Ask volume: <b id="askVol">—</b></span></div><div id="domText" style="margin-top:5px;font-size:12px;font-weight:800">Баланс сторон</div></div>
</div>

<div class="card s7"><div class="label">Открытые позиции DEMO</div><table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr><th>Пара</th><th>Сторона</th><th>Размер</th><th>Entry</th><th>Mark</th><th>PnL</th></tr></thead><tbody id="positions"><tr><td colspan="6" class="mut">Нет открытых позиций</td></tr></tbody></table></div>
<div class="card s5"><div class="label">Системный журнал</div><div id="log" class="log"></div></div>
</div>
<div class="foot"><span>Режим: <b class="cyan">DEMO</b></span><span>Плечо: <b id="lev">3×</b></span><span>Риск: <b id="risk">0,5%</b></span><span>Порог: <b>77%</b></span><span>TP: Auto</span><span>SL: Auto</span><span>Обновление рынка: WebSocket</span></div>
</div>
<script>
const API='';
const F=(n,d=4)=>n==null||n===''?'—':Number(n).toLocaleString('ru-RU',{maximumFractionDigits:d});
let ws=null,reconnectTimer=null,lastWsAt=0,lastAnalysisAt=0,botRunning=false;
let state={price:null,mark:null,bid:null,ask:null,bids:[],asks:[],changePct:null,changeAbs:null,high:null,low:null,funding:null,nextFunding:null};
function log(x){const e=document.getElementById('log');e.textContent+=`[${new Date().toLocaleTimeString()}] ${x}\n`;e.scrollTop=e.scrollHeight}
async function call(path,opt={}){const r=await fetch(API+path,{...opt,headers:{accept:'application/json'},cache:'no-store'});let j={};try{j=await r.json()}catch(_){ }if(!r.ok)throw Error(j.detail||r.status);return j}
function badge(el,t,c){el.textContent=t;el.className='badge '+c}
function cumulative(rows){let s=0;return rows.map(x=>{s+=Number(x[1]||0);return [Number(x[0]),Number(x[1]),s]})}
function calcDom(){const bv=(state.bids||[]).slice(0,10).reduce((a,x)=>a+Number(x[1]||0),0);const av=(state.asks||[]).slice(0,10).reduce((a,x)=>a+Number(x[1]||0),0);const total=bv+av||1;const bp=bv/total*100,ap=100-bp;bidDom.textContent=bp.toFixed(0)+'%';askDom.textContent=ap.toFixed(0)+'%';bidVol.textContent=F(bv,3);askVol.textContent=F(av,3);domLine.style.background=`linear-gradient(90deg,var(--green) 0 ${bp}%,var(--red) ${bp}% 100%)`;domText.textContent=bp>56?'ПОКУПАТЕЛИ ПРЕОБЛАДАЮТ':ap>56?'ПРОДАВЦЫ ПРЕОБЛАДАЮТ':'БАЛАНС СТОРОН';domText.className=bp>56?'green':ap>56?'red':'amber';return {bp,ap}}
function renderMarket(){livePrice.textContent=F(state.price,8);lastPriceMid.textContent=F(state.price,8);markPrice.textContent=F(state.mark,8);high24.textContent=F(state.high,8);low24.textContent=F(state.low,8);if(state.changePct!=null){change24.textContent=(state.changePct>=0?'+':'')+state.changePct.toFixed(2)+'%';change24.className='statv '+(state.changePct>=0?'green':'red')}changeAbs.textContent=F(state.changeAbs,4);funding.textContent=state.funding==null?'—':(state.funding*100).toFixed(4)+'%';funding.className='statv '+((state.funding||0)>=0?'green':'red');if(state.nextFunding){const d=Math.max(0,state.nextFunding-Date.now());fundingCd.textContent=new Date(d).toISOString().slice(11,19)}const ac=cumulative(state.asks||[]),bc=cumulative(state.bids||[]);asks.innerHTML=ac.slice(0,10).map(x=>`<tr><td class="red">${F(x[0],8)}</td><td>${F(x[1],4)}</td><td>${F(x[2],4)}</td></tr>`).join('');bids.innerHTML=bc.slice(0,10).map(x=>`<tr><td class="green">${F(x[0],8)}</td><td>${F(x[1],4)}</td><td>${F(x[2],4)}</td></tr>`).join('');if(state.ask&&state.bid)spread.textContent=F(state.ask-state.bid,8);calcDom()}
function deriveDirection(q){let ls=Number(q?.indicators?.long_score||0),ss=Number(q?.indicators?.short_score||0);const dom=calcDom();if(ls+ss<=0){ls=dom.bp;ss=dom.ap}else{const sum=ls+ss;ls=ls/sum*100;ss=100-ls;ls=ls*.75+dom.bp*.25;ss=100-ls}const bp=Math.max(0,Math.min(100,ls)),sp=100-bp;buyPct.textContent=bp.toFixed(0)+'%';sellPct.textContent=sp.toFixed(0)+'%';splitMarker.style.left=bp+'%';scoreGauge.style.background=`conic-gradient(var(--green) 0deg ${bp*3.6}deg,var(--red) ${bp*3.6}deg 360deg)`;let dir='НЕОПРЕДЕЛЕННО',cls='amber';if(bp>=58){dir='ВВЕРХ ↑';cls='green'}else if(sp>=58){dir='ВНИЗ ↓';cls='red'}direction.textContent=dir;direction.className=cls;const mood=(bp-50)*2;moodNeedle.style.left=((mood+100)/2)+'%';if(mood>=35){moodText.textContent='BULLISH +'+mood.toFixed(0);moodText.className='green'}else if(mood<=-35){moodText.textContent='BEARISH '+mood.toFixed(0);moodText.className='red'}else{moodText.textContent='NEUTRAL '+(mood>=0?'+':'')+mood.toFixed(0);moodText.className='amber'}}
function drawBot(s){botRunning=!!s.auto_enabled;badge(botBadge,'BOT • '+(botRunning?'RUNNING':'STOPPED'),botRunning?'ok':'bad');searchDot.style.display=botRunning?'inline-block':'none';searchText.textContent=botRunning?'ИДЁТ ПОИСК ТОЧКИ ВХОДА…':'ПОИСК ОСТАНОВЛЕН';lev.textContent=(s.leverage||3)+'×';risk.textContent=F((s.risk_per_trade||0)*100,2)+'%';threshold.textContent=F((s.confidence_threshold||.77)*100,0)+'%';const q=s.runtime?.last_signal||{};lastAnalysisAt=s.runtime?.last_scan_at?Number(s.runtime.last_scan_at)*1000:lastAnalysisAt;const a=String(q.action||'HOLD').toUpperCase();signalLine.textContent=(q.symbol?`${q.symbol} `:'')+a;signalLine.className='signal '+(a==='BUY'?'green':a==='SELL'?'red':'amber');conf.textContent=F(Number(q.confidence||0)*100,0)+'%';marketState.textContent=q.market_state||'—';rsi.textContent=F(q.indicators?.rsi,1);adx.textContent=F(q.indicators?.adx,1);volRatio.textContent=q.indicators?.volume_ratio?F(q.indicators.volume_ratio,2)+'×':'—';entry.textContent=F(q.entry,8);sl.textContent=F(q.stop_loss,8);tp.textContent=F(q.take_profit,8);deriveDirection(q);const ps=s.positions||[];positions.innerHTML=ps.length?ps.map(p=>{const long=Number(p.position_amt)>0,pnl=Number(p.unrealized_profit||0);return `<tr><td>${p.symbol}</td><td class="${long?'green':'red'}">${long?'LONG':'SHORT'}</td><td>${F(Math.abs(p.position_amt),8)}</td><td>${F(p.entry_price,8)}</td><td>${F(p.mark_price,8)}</td><td class="${pnl>=0?'green':'red'}">${F(pnl,4)}</td></tr>`}).join(''):'<tr><td colspan="6" class="mut">Нет открытых позиций</td></tr>'}
async function refreshStatus(){try{drawBot(await call('/bot/status'))}catch(e){badge(botBadge,'BOT • ERROR','bad');log('Status: '+e.message)}}
async function health(){try{await call('/health');badge(serverBadge,'SERVER • ONLINE','ok')}catch(e){badge(serverBadge,'SERVER • OFFLINE','bad')}}
function connectWs(){clearTimeout(reconnectTimer);if(ws){ws.onclose=null;try{ws.close()}catch(_){}}state={price:null,mark:null,bid:null,ask:null,bids:[],asks:[],changePct:null,changeAbs:null,high:null,low:null,funding:null,nextFunding:null};const s=marketSymbol.value.toLowerCase();const streams=`${s}@aggTrade/${s}@bookTicker/${s}@depth10@100ms/${s}@ticker/${s}@markPrice@1s`;try{ws=new WebSocket('wss://fstream.binance.com/stream?streams='+streams)}catch(e){reconnectTimer=setTimeout(connectWs,2500);return}badge(binanceBadge,'BINANCE • CONNECTING','wait');ws.onopen=()=>{badge(binanceBadge,'BINANCE • LIVE','ok');log('WebSocket connected: '+marketSymbol.value)};ws.onmessage=ev=>{try{const m=JSON.parse(ev.data),d=m.data||{},st=m.stream||'';lastWsAt=Date.now();if(st.endsWith('@aggTrade'))state.price=Number(d.p);else if(st.endsWith('@bookTicker')){state.bid=Number(d.b);state.ask=Number(d.a)}else if(st.includes('@depth10')){state.bids=d.b||[];state.asks=d.a||[]}else if(st.endsWith('@ticker')){state.changePct=Number(d.P);state.changeAbs=Number(d.p);state.high=Number(d.h);state.low=Number(d.l)}else if(st.includes('@markPrice')){state.mark=Number(d.p);state.funding=Number(d.r);state.nextFunding=Number(d.T)}renderMarket()}catch(e){}};ws.onerror=()=>badge(binanceBadge,'BINANCE • WS ERROR','bad');ws.onclose=()=>{badge(binanceBadge,'BINANCE • RECONNECT','wait');reconnectTimer=setTimeout(connectWs,2500)}}
function ages(){const a=lastWsAt?Math.round((Date.now()-lastWsAt)/100)/10:null;liveAge.textContent='LIVE '+(a==null?'—':a+'s');liveAge.className='badge '+(a!=null&&a<2?'ok':a!=null&&a<8?'wait':'bad');analysisAge.textContent=lastAnalysisAt?Math.max(0,Math.round((Date.now()-lastAnalysisAt)/1000))+'s ago':'—';if(lastWsAt&&Date.now()-lastWsAt>10000&&ws?.readyState===WebSocket.OPEN)try{ws.close()}catch(_){}}
async function startBot(){if(confirm('Запустить AUTO DEMO с порогом 77%?'))try{drawBot(await call('/bot/start?confirm=true',{method:'POST'}));log('AUTO START')}catch(e){alert(e.message)}}async function stopBot(){try{drawBot(await call('/bot/stop',{method:'POST'}));log('STOP AUTO')}catch(e){alert(e.message)}}async function emergency(){if(confirm('Запретить новые входы?'))try{const d=await call('/bot/emergency-stop',{method:'POST'});drawBot(d.status||d);log('EMERGENCY STOP')}catch(e){alert(e.message)}}async function closeAll(){if(prompt('Введите CLOSE ALL для подтверждения')==='CLOSE ALL')try{const d=await call('/bot/close-all?confirm=true',{method:'POST'});drawBot(d.status||d);log('CLOSE ALL')}catch(e){alert(e.message)}}
health();refreshStatus();connectWs();setInterval(refreshStatus,5000);setInterval(health,15000);setInterval(ages,500);log('Premium panel v0.5.3 loaded');
</script></body></html>'''