PANEL_HTML = r'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Scalping AI Panel</title>
<style>
:root{--bg:#081018;--panel:#101a24;--line:#223240;--text:#eef5fb;--mut:#91a4b4;--green:#35d08c;--red:#ff5d6c;--amber:#f6c453;--blue:#42a5ff}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Arial,sans-serif}.w{max-width:1500px;margin:auto;padding:10px 14px}.g{display:grid;grid-template-columns:repeat(12,1fr);gap:9px}.c{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:12px}.s3{grid-column:span 3}.s4{grid-column:span 4}.s5{grid-column:span 5}.s6{grid-column:span 6}.s7{grid-column:span 7}.s8{grid-column:span 8}.s12{grid-column:span 12}.lab{font-size:11px;color:var(--mut);text-transform:uppercase}.big{font-size:25px;font-weight:800}.mut{color:var(--mut)}h1{font-size:25px;margin:0 0 2px}.statusbar{display:flex;gap:6px;flex-wrap:wrap;margin:5px 0 9px}.badge{padding:5px 8px;border-radius:999px;font-size:11px;font-weight:800;border:1px solid var(--line)}.ok{background:#0d3426;color:#aaf1cf;border-color:#1f644a}.bad{background:#3a171b;color:#ffadb5;border-color:#743039}.wait{background:#3b3214;color:#ffe19a;border-color:#716126}.btns{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}button,select{padding:9px;border:0;border-radius:9px;font-weight:800}.start{background:#168d62;color:white}.stop{background:#536779;color:white}.emg{background:#c43b4b;color:white}.close{background:#8e2a34;color:white}.price{font-size:31px;font-weight:900}.bid{color:var(--green)}.ask{color:var(--red)}.signal.buy{color:var(--green)}.signal.sell{color:var(--red)}.signal.hold{color:var(--amber)}.book{display:grid;grid-template-columns:1fr 1fr;gap:10px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:5px;border-bottom:1px solid var(--line);text-align:left}.split{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}.meter{height:14px;background:#1d2b37;border-radius:999px;overflow:hidden;display:flex}.longbar{background:var(--green);height:100%}.shortbar{background:var(--red);height:100%}.scan{display:flex;align-items:center;gap:8px;font-size:12px;font-weight:700}.spin{width:10px;height:10px;border-radius:50%;background:var(--blue);box-shadow:0 0 0 0 rgba(66,165,255,.7);animation:pulse 1.1s infinite}@keyframes pulse{70%{box-shadow:0 0 0 8px rgba(66,165,255,0)}100%{box-shadow:0 0 0 0 rgba(66,165,255,0)}}.log{height:92px;overflow:auto;background:#071019;border:1px solid var(--line);border-radius:9px;padding:8px;white-space:pre-wrap;font:11px monospace}.tiny{font-size:11px;color:var(--mut)}
@media(max-width:980px){.s3,.s4,.s5,.s6,.s7,.s8{grid-column:span 12}.btns{grid-template-columns:1fr 1fr}.book{grid-template-columns:1fr}}@media(max-width:520px){.btns{grid-template-columns:1fr}.w{padding:8px}}
</style></head><body><div class="w">
<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:12px"><div><h1>Scalping AI Control Panel</h1><div class="mut" style="font-size:12px">DEMO execution + LIVE Binance USD-M WebSocket</div></div><div class="statusbar"><span id="serverBadge" class="badge wait">SERVER</span><span id="binanceBadge" class="badge wait">BINANCE</span><span id="botBadge" class="badge bad">BOT STOPPED</span><span id="wsAge" class="badge">LIVE —</span></div></div>
<div class="g">
<div class="c s3"><div class="lab">AUTO</div><div class="big"><span id="auto">STOPPED</span></div></div><div class="c s3"><div class="lab">Баланс DEMO</div><div id="bal" class="big">—</div></div><div class="c s3"><div class="lab">Доступно</div><div id="avail" class="big">—</div></div><div class="c s3"><div class="lab">Плечо / риск</div><div class="big"><span id="lev">3×</span> / <span id="risk">0,5%</span></div></div>
<div class="c s12"><div class="btns"><button class="start" onclick="startBot()">▶ AUTO START</button><button class="stop" onclick="stopBot()">■ STOP AUTO</button><button class="emg" onclick="emergency()">⚠ EMERGENCY STOP</button><button class="close" onclick="closeAll()">✖ CLOSE ALL</button></div></div>

<div class="c s4"><div style="display:flex;justify-content:space-between;align-items:center"><div class="lab">LIVE цена / сигнал</div><select id="marketSymbol" onchange="connectMarketWs()"><option>BTCUSDT</option><option>ETHUSDT</option><option>BNBUSDT</option><option>SOLUSDT</option></select></div><div id="livePrice" class="price" style="margin-top:6px">—</div><div style="display:flex;gap:12px;font-size:13px"><span class="bid">Bid <b id="bestBid">—</b></span><span class="ask">Ask <b id="bestAsk">—</b></span></div><hr style="border:0;border-top:1px solid var(--line);margin:9px 0"><div class="scan"><span id="scanDot" class="spin" style="display:none"></span><span id="scanText">Поиск остановлен</span><span class="mut" id="scanAge"></span></div><div id="signalLine" class="big signal hold" style="margin-top:5px"><span id="sym">—</span> <span id="act">HOLD</span></div><div class="split"><div><span class="bid">BUY / LONG</span> <b id="buyPct">50%</b></div><div style="text-align:right"><span class="ask">SELL / SHORT</span> <b id="sellPct">50%</b></div></div><div class="meter"><div id="longBar" class="longbar" style="width:50%"></div><div id="shortBar" class="shortbar" style="width:50%"></div></div><div style="margin-top:6px;font-size:12px">Направление: <b id="direction">НЕЙТРАЛЬНО</b> · Confidence <b id="conf">—</b> · Вход от <b id="thr">77%</b></div><div class="tiny" style="margin-top:4px">Entry <span id="entry">—</span> · SL <span id="sl">—</span> · TP <span id="tp">—</span> · <span id="mkt">—</span></div></div>

<div class="c s8"><div class="lab">Стакан LIVE Binance — топ 10</div><div class="book"><div><h3 class="ask" style="margin:6px 0">Продажа / ASK</h3><table><thead><tr><th>Цена</th><th>Кол-во</th></tr></thead><tbody id="asks"></tbody></table></div><div><h3 class="bid" style="margin:6px 0">Покупка / BID</h3><table><thead><tr><th>Цена</th><th>Кол-во</th></tr></thead><tbody id="bids"></tbody></table></div></div></div>

<div class="c s7"><div class="lab">Открытые позиции DEMO</div><table><thead><tr><th>Пара</th><th>Сторона</th><th>Размер</th><th>Entry</th><th>Mark</th><th>PnL</th></tr></thead><tbody id="pos"><tr><td colspan="6" class="mut">Нет позиций</td></tr></tbody></table></div><div class="c s5"><div class="lab">Системный журнал</div><div id="log" class="log" style="margin-top:6px"></div></div>
</div></div>
<script>
const API='';const F=(n,d=4)=>n==null||n===''?'—':Number(n).toLocaleString('ru-RU',{maximumFractionDigits:d});let ws=null,reTimer=null,lastWs=0,queued=false,live={price:null,bid:null,ask:null,bids:[],asks:[]};
function L(x){let e=log;e.textContent+=`[${new Date().toLocaleTimeString()}] ${x}\n`;e.scrollTop=e.scrollHeight}async function C(p,o={}){let r=await fetch(API+p,{...o,headers:{accept:'application/json'},cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.detail||r.status);return j}function setBadge(el,text,state){el.textContent=text;el.className='badge '+state}
function draw(s){let on=!!s.auto_enabled;auto.textContent=on?'RUNNING':'STOPPED';auto.style.color=on?'var(--green)':'var(--red)';setBadge(botBadge,on?'BOT RUNNING':'BOT STOPPED',on?'ok':'bad');scanDot.style.display=on?'inline-block':'none';scanText.textContent=on?'Идёт поиск точки входа…':'Поиск остановлен';bal.textContent=F(s.balance?.balance);avail.textContent=F(s.balance?.available_balance);lev.textContent=(s.leverage||3)+'×';risk.textContent=F((s.risk_per_trade||0)*100,2)+'%';thr.textContent=F((s.confidence_threshold||.77)*100,0)+'%';let q=s.runtime?.last_signal||{};sym.textContent=q.symbol||'—';act.textContent=q.action||'HOLD';let a=String(q.action||'HOLD').toUpperCase(),cl=a==='BUY'?'buy':a==='SELL'?'sell':'hold';signalLine.className='big signal '+cl;conf.textContent=F(Number(q.confidence||0)*100,1)+'%';entry.textContent=F(q.entry,8);sl.textContent=F(q.stop_loss,8);tp.textContent=F(q.take_profit,8);mkt.textContent=q.market_state||'—';let ls=Number(q.indicators?.long_score||0),ss=Number(q.indicators?.short_score||0),sum=ls+ss,buy=sum?Math.round(ls/sum*100):50,sell=100-buy;buyPct.textContent=buy+'%';sellPct.textContent=sell+'%';longBar.style.width=buy+'%';shortBar.style.width=sell+'%';direction.textContent=buy>=58?'ВВЕРХ ↑':sell>=58?'ВНИЗ ↓':'НЕОПРЕДЕЛЕННО';direction.style.color=buy>=58?'var(--green)':sell>=58?'var(--red)':'var(--amber)';let last=Number(s.runtime?.last_scan_at||0);scanAge.textContent=last?'последний анализ '+Math.max(0,Math.round(Date.now()/1000-last))+'с назад':'';let ps=s.positions||[];pos.innerHTML=ps.length?ps.map(p=>{let lng=Number(p.position_amt)>0,pnl=Number(p.unrealized_profit||0);return `<tr><td>${p.symbol}</td><td class="${lng?'bid':'ask'}">${lng?'LONG':'SHORT'}</td><td>${F(Math.abs(p.position_amt),8)}</td><td>${F(p.entry_price,8)}</td><td>${F(p.mark_price,8)}</td><td class="${pnl>=0?'bid':'ask'}">${F(pnl)}</td></tr>`}).join(''):'<tr><td colspan="6" class="mut">Нет позиций</td></tr>'}
async function status(){try{draw(await C('/bot/status'))}catch(e){setBadge(botBadge,'BOT ERROR','bad');L('Статус: '+e.message)}}async function health(){try{await C('/health');setBadge(serverBadge,'SERVER ONLINE','ok')}catch(e){setBadge(serverBadge,'SERVER OFFLINE','bad')}}function render(){queued=false;livePrice.textContent=F(live.price,8);bestBid.textContent=F(live.bid,8);bestAsk.textContent=F(live.ask,8);asks.innerHTML=(live.asks||[]).slice(0,10).map(x=>`<tr><td class="ask">${F(x[0],8)}</td><td>${F(x[1],5)}</td></tr>`).join('');bids.innerHTML=(live.bids||[]).slice(0,10).map(x=>`<tr><td class="bid">${F(x[0],8)}</td><td>${F(x[1],5)}</td></tr>`).join('')}function qrender(){if(!queued){queued=true;requestAnimationFrame(render)}}
function connectMarketWs(){clearTimeout(reTimer);if(ws){ws.onclose=null;try{ws.close()}catch(_){}}let s=marketSymbol.value.toLowerCase(),streams=`${s}@aggTrade/${s}@bookTicker/${s}@depth10@100ms`;setBadge(binanceBadge,'BINANCE CONNECTING','wait');ws=new WebSocket('wss://fstream.binance.com/stream?streams='+streams);ws.onopen=()=>{setBadge(binanceBadge,'BINANCE LIVE','ok');L('WebSocket: '+marketSymbol.value)};ws.onmessage=e=>{let m=JSON.parse(e.data),d=m.data||{},st=m.stream||'';lastWs=Date.now();if(st.endsWith('@aggTrade'))live.price=Number(d.p);else if(st.endsWith('@bookTicker')){live.bid=Number(d.b);live.ask=Number(d.a)}else if(st.includes('@depth10')){live.bids=d.b||[];live.asks=d.a||[]}qrender()};ws.onerror=()=>setBadge(binanceBadge,'BINANCE ERROR','bad');ws.onclose=()=>{setBadge(binanceBadge,'BINANCE RECONNECT','wait');reTimer=setTimeout(connectMarketWs,2200)}}
function ages(){let a=lastWs?Math.round((Date.now()-lastWs)/1000):null;wsAge.textContent='LIVE '+(a==null?'—':a+'s');wsAge.className='badge '+(a!=null&&a<3?'ok':a!=null&&a<10?'wait':'bad')}
async function startBot(){if(confirm('Запустить AUTO DEMO с порогом 77%?'))try{draw(await C('/bot/start?confirm=true',{method:'POST'}));L('AUTO START')}catch(e){alert(e.message)}}async function stopBot(){try{draw(await C('/bot/stop',{method:'POST'}));L('STOP AUTO')}catch(e){alert(e.message)}}async function emergency(){if(confirm('Запретить новые входы?'))try{let d=await C('/bot/emergency-stop',{method:'POST'});draw(d.status||d);L('EMERGENCY STOP')}catch(e){alert(e.message)}}async function closeAll(){if(prompt('Введите CLOSE ALL')==='CLOSE ALL')try{let d=await C('/bot/close-all?confirm=true',{method:'POST'});draw(d.status||d);L('CLOSE ALL')}catch(e){alert(e.message)}}
health();status();connectMarketWs();setInterval(status,5000);setInterval(health,15000);setInterval(ages,1000);L('Compact panel v0.5.2');
</script></body></html>'''