PANEL_HTML = r'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Scalping AI Panel</title>
<style>
:root{--bg:#081018;--panel:#101a24;--line:#223240;--text:#eef5fb;--mut:#91a4b4;--green:#35d08c;--red:#ff5d6c;--amber:#f6c453;--blue:#42a5ff}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Arial,sans-serif}.w{max-width:1450px;margin:auto;padding:20px}.g{display:grid;grid-template-columns:repeat(12,1fr);gap:12px}.c{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.s3{grid-column:span 3}.s4{grid-column:span 4}.s6{grid-column:span 6}.s8{grid-column:span 8}.s12{grid-column:span 12}.lab{font-size:12px;color:var(--mut);text-transform:uppercase}.big{font-size:28px;font-weight:700;margin-top:8px}.mut{color:var(--mut)}.btns{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}button,select{padding:12px;border:0;border-radius:10px;font-weight:700}.start{background:#168d62;color:#fff}.stop{background:#536779;color:#fff}.emg{background:#c43b4b;color:#fff}.close{background:#8e2a34;color:#fff}.ref{background:#164a70;color:#fff}.dot{display:inline-block;width:11px;height:11px;border-radius:50%;background:var(--red);margin-right:8px}.dot.on{background:var(--green)}.bar{height:16px;background:#1d2b37;border-radius:20px;overflow:hidden;margin:10px 0}.fill{height:100%;width:0;background:var(--amber);transition:width .25s,background .25s}.signal.buy{color:var(--green)}.signal.sell{color:var(--red)}.signal.hold{color:var(--amber)}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid var(--line);text-align:left}.price{font-size:34px;font-weight:800}.bid{color:var(--green)}.ask{color:var(--red)}.book{display:grid;grid-template-columns:1fr 1fr;gap:16px}.book table{font-size:13px}.livebadge{display:inline-block;padding:5px 9px;border-radius:999px;background:#0f5132;color:#aaf1cf;font-size:12px;font-weight:700}.log{height:160px;overflow:auto;background:#071019;border:1px solid var(--line);border-radius:10px;padding:10px;white-space:pre-wrap;font-family:monospace;font-size:12px}@media(max-width:950px){.s3,.s4,.s6,.s8{grid-column:span 12}.btns{grid-template-columns:1fr 1fr}.book{grid-template-columns:1fr}}@media(max-width:520px){.btns{grid-template-columns:1fr}.w{padding:10px}.price{font-size:28px}}
</style></head>
<body><div class="w"><h1>Scalping AI Control Panel</h1><div class="mut" style="margin-bottom:18px">Binance Futures DEMO execution + LIVE Binance USD-M market data</div>
<div class="g">
<div class="c s3"><div class="lab">AUTO</div><div class="big"><span id="dot" class="dot"></span><span id="auto">STOPPED</span></div></div>
<div class="c s3"><div class="lab">Баланс DEMO USDT</div><div id="bal" class="big">—</div></div>
<div class="c s3"><div class="lab">Доступно</div><div id="avail" class="big">—</div></div>
<div class="c s3"><div class="lab">Плечо / риск</div><div class="big"><span id="lev">3×</span> / <span id="risk">0.5%</span></div></div>
<div class="c s12"><div class="lab">Управление</div><div class="btns" style="margin-top:10px"><button class="start" onclick="startBot()">▶ AUTO START</button><button class="stop" onclick="stopBot()">■ STOP AUTO</button><button class="emg" onclick="emergency()">⚠ EMERGENCY STOP</button><button class="close" onclick="closeAll()">✖ CLOSE ALL</button></div></div>

<div class="c s4">
<div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div class="lab">Реальная цена Binance Futures</div><span class="livebadge">LIVE</span></div>
<div style="margin:12px 0"><select id="marketSymbol" onchange="marketTick()"><option>BTCUSDT</option><option>ETHUSDT</option><option>BNBUSDT</option><option>SOLUSDT</option></select></div>
<div id="livePrice" class="price">—</div><div style="display:flex;gap:18px;margin-top:10px"><span class="bid">Bid: <b id="bestBid">—</b></span><span class="ask">Ask: <b id="bestAsk">—</b></span></div><div class="mut" style="font-size:12px;margin-top:10px">Обновление примерно раз в 1 секунду. Это LIVE market data, а сделки пока исполняются в Binance DEMO.</div>
</div>

<div class="c s8"><div class="lab">Стакан LIVE Binance — топ 10</div><div class="book"><div><h3 class="ask">Продажа / ASK</h3><table><thead><tr><th>Цена</th><th>Количество</th></tr></thead><tbody id="asks"></tbody></table></div><div><h3 class="bid">Покупка / BID</h3><table><thead><tr><th>Цена</th><th>Количество</th></tr></thead><tbody id="bids"></tbody></table></div></div></div>

<div class="c s6"><div class="lab">Лучший сигнал</div><div class="big signal hold" id="signalLine"><span id="sym">—</span> <span id="act">HOLD</span></div><div class="bar"><div id="fill" class="fill"></div></div><div>Confidence score: <b id="conf">—</b> • Порог входа: <b id="thr">77%</b></div><table><tr><th>Entry signal</th><td id="entry">—</td><th>SL</th><td id="sl">—</td></tr><tr><th>TP</th><td id="tp">—</td><th>Market</th><td id="mkt">—</td></tr></table><div class="mut" style="font-size:12px;margin-top:10px">77% — внутренний score стратегии, не статистически гарантированная вероятность выигрыша.</div></div>
<div class="c s6"><div class="lab">Открытые позиции DEMO</div><table><thead><tr><th>Пара</th><th>Сторона</th><th>Размер</th><th>Entry</th><th>Mark</th><th>PnL</th></tr></thead><tbody id="pos"><tr><td colspan="6" class="mut">Нет позиций</td></tr></tbody></table></div>
<div class="c s12"><button class="ref" onclick="refreshStatus()">↻ Обновить статус</button><div id="log" class="log" style="margin-top:10px"></div></div>
</div></div>
<script>
const API='';const F=(n,d=4)=>n==null?'—':Number(n).toLocaleString('ru-RU',{maximumFractionDigits:d});
function L(x){let e=document.getElementById('log');e.textContent+=`[${new Date().toLocaleTimeString()}] ${x}\n`;e.scrollTop=e.scrollHeight}
async function C(p,o={}){let r=await fetch(API+p,{...o,headers:{accept:'application/json'},cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.detail||r.status);return j}
function signalColor(a){a=String(a||'HOLD').toUpperCase();return a==='BUY'?'buy':a==='SELL'?'sell':'hold'}
function draw(s){let on=!!s.auto_enabled;dot.className='dot '+(on?'on':'');auto.textContent=on?'RUNNING':'STOPPED';bal.textContent=F(s.balance?.balance);avail.textContent=F(s.balance?.available_balance);lev.textContent=(s.leverage||3)+'×';risk.textContent=F((s.risk_per_trade||0)*100,2)+'%';thr.textContent=F((s.confidence_threshold||.77)*100,1)+'%';let q=s.runtime?.last_signal||{};sym.textContent=q.symbol||'—';act.textContent=q.action||'HOLD';let col=signalColor(q.action);signalLine.className='big signal '+col;let c=Number(q.confidence||0);conf.textContent=F(c*100,2)+'%';fill.style.width=Math.min(100,c*100)+'%';fill.style.background=col==='buy'?'var(--green)':col==='sell'?'var(--red)':'var(--amber)';entry.textContent=F(q.entry,8);sl.textContent=F(q.stop_loss,8);tp.textContent=F(q.take_profit,8);mkt.textContent=q.market_state||'—';let ps=s.positions||[];pos.innerHTML=ps.length?ps.map(p=>{let long=Number(p.position_amt)>0,pnl=Number(p.unrealized_profit||0);return `<tr><td>${p.symbol}</td><td class="${long?'bid':'ask'}">${long?'LONG':'SHORT'}</td><td>${F(Math.abs(p.position_amt),8)}</td><td>${F(p.entry_price,8)}</td><td>${F(p.mark_price,8)}</td><td class="${pnl>=0?'bid':'ask'}">${F(pnl)}</td></tr>`}).join(''):'<tr><td colspan="6" class="mut">Нет позиций</td></tr>'}
async function refreshStatus(){try{draw(await C('/bot/status'))}catch(e){L('Статус: '+e.message)}}
async function marketTick(){try{let s=marketSymbol.value,d=await C('/market/live?symbol='+encodeURIComponent(s));livePrice.textContent=F(d.price,8);bestBid.textContent=F(d.bid,8);bestAsk.textContent=F(d.ask,8);asks.innerHTML=(d.asks||[]).map(x=>`<tr><td class="ask">${F(x[0],8)}</td><td>${F(x[1],5)}</td></tr>`).join('');bids.innerHTML=(d.bids||[]).map(x=>`<tr><td class="bid">${F(x[0],8)}</td><td>${F(x[1],5)}</td></tr>`).join('')}catch(e){L('LIVE market: '+e.message)}}
async function startBot(){if(confirm('Запустить AUTO на DEMO с порогом 77%?'))try{draw(await C('/bot/start?confirm=true',{method:'POST'}));L('AUTO START')}catch(e){alert(e.message)}}
async function stopBot(){try{draw(await C('/bot/stop',{method:'POST'}));L('STOP AUTO')}catch(e){alert(e.message)}}
async function emergency(){if(confirm('Запретить новые входы?'))try{let d=await C('/bot/emergency-stop',{method:'POST'});draw(d.status||d);L('EMERGENCY STOP')}catch(e){alert(e.message)}}
async function closeAll(){if(prompt('Введите CLOSE ALL для подтверждения')==='CLOSE ALL')try{let d=await C('/bot/close-all?confirm=true',{method:'POST'});draw(d.status||d);L('CLOSE ALL')}catch(e){alert(e.message)}}
refreshStatus();marketTick();setInterval(refreshStatus,3000);setInterval(marketTick,1000);L('Панель v0.5 запущена');
</script></body></html>'''